"""Platform subtitles from the video page (YouTube and other yt-dlp sites)."""

from __future__ import annotations

import logging
import time
from pathlib import Path

from app.core.subtitle_formats import parse_subtitle_text
from app.providers.base import (
    AUTO, MANUAL, ProviderError, ProviderUnavailable, SubtitleEvidence, SubtitleRequest,
)

log = logging.getLogger(__name__)

PIVOT_LANGUAGE = "en"
MAX_TRACKS = 5
DELAY_BETWEEN_S = 1.0


def _base(code: str) -> str:
    return code.split("-")[0].lower()


def _match(tracks: dict, language: str) -> str | None:
    """Exact code first, then a regional variant (tr-TR), never an auto-translation of another track."""
    if language in tracks:
        return language
    for code in sorted(tracks):
        if _base(code) == language and not code.endswith("-orig"):
            return code
    return None


def select_tracks(info: dict, source_language: str, target_language: str) -> list[tuple[str, bool, str]]:
    """Return (track code, automatic, evidence kind) in priority order."""
    manual = info.get("subtitles") or {}
    auto = info.get("automatic_captions") or {}
    chosen: list[tuple[str, bool, str]] = []
    for language in dict.fromkeys([source_language, target_language, PIVOT_LANGUAGE]):
        code = _match(manual, language)
        if code:
            chosen.append((code, False, MANUAL))
    # The platform's own ASR track is labelled "<lang>-orig"; it may be in the wrong language.
    originals = [code for code in auto if code.endswith("-orig")]
    if originals:
        chosen.append((originals[0], True, AUTO))
    elif _match(auto, source_language):
        chosen.append((_match(auto, source_language), True, AUTO))
    # Platform auto-translations of the target language are not fetched: they are machine translations of the
    # platform's own (often wrong-language) ASR, unused in the output, and each request risks HTTP 429.
    return chosen[:MAX_TRACKS]


class PlatformSubtitleProvider:
    name = "youtube"

    def __init__(self, adapter, sleep=time.sleep):
        self._adapter = adapter
        self._sleep = sleep

    def fetch(self, request: SubtitleRequest) -> list[SubtitleEvidence]:
        if not request.url or not request.media_info:
            raise ProviderUnavailable("not a URL input")
        tracks = select_tracks(request.media_info, request.source_language, request.target_language)
        if not tracks:
            log.info("No platform subtitles available")
            return []
        evidence = []
        failures = []
        for index, (code, automatic, kind) in enumerate(tracks):
            if index:
                self._sleep(DELAY_BETWEEN_S)
            try:
                path = self._adapter.download_subtitle(request.url, code, automatic, Path(request.work_dir))
                text = path.read_text(encoding="utf-8-sig")
            except ProviderUnavailable as exc:
                log.info("Platform subtitle %s unavailable: %s", code, exc)    # not an error: Whisper is the source
                break
            except ProviderError as exc:
                failures.append(f"{code}: {exc}")
                log.warning("Platform subtitle %s failed: %s", code, exc)
                if exc.retryable:
                    break   # Rate limited: stop asking for more tracks.
                continue
            cues = parse_subtitle_text(text, rolling=automatic)
            language = code[:-5] if code.endswith("-orig") else code
            notes = [] if kind == MANUAL else ["machine generated by the platform"]
            evidence.append(SubtitleEvidence(
                provider=self.name, language=_base(language), kind=kind, cues=cues,
                reference=f"{'auto' if automatic else 'manual'}:{code}", machine_generated=automatic, notes=notes))
        if failures and not evidence:
            raise ProviderError("; ".join(failures))
        return evidence
